[package]
name = "scouting"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
ws = "0.9.1"
serde_json = "1.0.48"
serde = { version = "1.0.104", features = ["derive"] }
ring = "0.16.11"
